Assets/Scripts/Player/HouseInputManager.cs
- I also done some of the TODOs in the `HouseInputManager` script, and I change the status to "REVIEW". Just remove the comment if you're satisfied with the changes.
=> Fixed camera rotation not working when no furniture is selected

Assets/Scripts/ExtensionMethods.cs, Assets/Scripts/ExtensionMethods.cs.meta, Assets/Scripts/Player/HouseInputManager.cs, Assets/Scripts/Spawner.cs, Assets/Scripts/Spawner.cs.meta, Assets/Scripts/SpawnerManger.cs, Assets/Scripts/SpawnerManger.cs.meta, ProjectSettings/EditorBuildSettings.asset
Made changes based on discussion with Kai
=> Simplified raycast function and merged the two mousedown events, Implemented Spawning

Assets/Prefabs/Door.prefab, Assets/Scripts/Player/HouseInputManager.cs, Assets/Scripts/Player/HuntingInputManager.cs, ProjectSettings/ShaderGraphSettings.asset, ProjectSettings/TagManager.asset
- Reworked `Door` prefab, further seperating fucntionality and display
- Added door layer
- Changed checks to either use a layermask on the raycast or a layer check
=> Converted door checks to use layers

Assets/Scripts/SensesDemo.cs, Assets/Scripts/SensesDemo.cs.meta
=> Added script to help show furniture senses

Assets/Prefabs/UI/Alert UI.prefab, Assets/Scenes/House.unity, Assets/Scripts/Player/HouseInputManager.cs, Assets/Scripts/UI/ShopUIManager.cs
Fixed https://trello.com/c/zkV7ctzB/96-buttons-dont-disappear-when-removing-furniture and https://trello.com/c/bdsLiQJr/97-money-duplication
=> Fixed bugs

Assets/Prefabs/Placeable/Placeable_Chair.prefab, Assets/Prefabs/Placeable/Placeable_Table.prefab, Assets/Prefabs/Shootable/Chair.prefab, Assets/Prefabs/Shootable/Table.prefab, Assets/Scenes/ForestTestingEthan.unity, Assets/Scenes/House.unity, Assets/Scriptable Objects/Chair.asset, Assets/Scriptable Objects/Table.asset, Assets/Scripts/Placeable/Placeable.cs, Assets/Scripts/Player/HouseInputManager.cs, Assets/Scripts/Shootable/Shootable.cs, Assets/Scripts/UI/Item Thumbnail UI/DecorateListItem.cs
Implemented different sizes and materials for furnitures.
=> Furniture variety

Assets/Input/PlayerInput.cs, Assets/Input/PlayerInput.inputactions, Assets/Scripts/Managers/WeaponManager.cs, Assets/Scripts/Player/HuntingInputManager.cs
You can now hotswitch by using the 1 to 6 keys to quickly select a weapon and also added a debug command on CTRL + R to give the player 100 rounds of ammo. Also modified the weapon handler to facilitate these changes.
=> Hot Switching + Debug Command

Assets/Scripts/Furnitures/Shootable/WanderAI.cs, ProjectSettings/ProjectSettings.asset
Forgot to wrap gizmo code in a `#if UNITY_EDITOR` directive
=> Fixed issue where code where editor code was being left in build

Assets/Input/PlayerInput.cs, Assets/Input/PlayerInput.inputactions, Assets/Input/PlayerInput.inputactions.meta, Assets/Prefabs/UI/Developer Console Canvas.prefab, Assets/Scenes/02_Hunting.unity, Assets/Scriptable Objects/Command/Give Ammo Command.asset, Assets/Scriptable Objects/Command/Give Ammo Command.asset.meta, Assets/Scripts/Managers/HuntingInputManager.cs, Assets/Scripts/Utils/Console/Commands/GiveAmmoCommand.cs, Assets/Scripts/Utils/Console/Commands/GiveAmmoCommand.cs.meta
Changed give ammo from `Ctrl` + `R` to `giveammo <number>` command instead
=> Added giveammo command

Assets/Scripts/Managers/SpawnerManager.cs, Assets/Scripts/Others/Spawner.cs, Assets/Scripts/Others/SpawnerGroup.cs, Assets/Scripts/Others/SpawnerGroup.cs.meta
Spawners have been cleaned up, new SpawnerGroup for spawning multiple furniture. #93 should be resolved before this is merged
=> Spawner fix

Assets/Prefabs/Weapons/Ammo_Arrow.prefab, Assets/Prefabs/Weapons/Ammo_Buckshot.prefab, Assets/Prefabs/Weapons/Ammo_RifleBullet.prefab, Assets/Scriptable Objects/SoundAlerts/ProjectileImpactSO.asset, Assets/Scriptable Objects/SoundAlerts/ProjectileImpactSO.asset.meta, Assets/Scripts/Weapons/Bullet.cs
Projectiles now make a soundalert for furniture when they hit something
=> Added soundalerts on projectile collision

Assets/Scripts/Furnitures/Shootable/Shootable.cs
Was a leftover from when code was being removed from FurnitureSOs
=> Fixed issue where furniture spawned with 0,0,0 scale

Assets/Scripts/Managers/HouseManager.cs
Bug description:
Place something in deco not at max distance (try to place as close to player as possible). When not at max distance the height (Y axis) of where the furni is placed is lower than when placing at maximum distance
This PR fixes that by setting the y position to be relative to the players y position, meaning it will no longer clip through the floor when placing close to yourself.
=> Fix placeable bug

Assets/Scripts/Scriptable Objects/InvestigateBehaviour.cs
dangerPosition now persists between frames
=> Tweaked investigate behaviour

Assets/Scripts/Managers/HouseManager.cs
Fixes issue in https://trello.com/c/UmwO7XpK
=> Fixed duplication glitch

Assets/Prefabs/UI/General/PauseCanvas.prefab, Assets/Scripts/UI/PauseMenu.cs
Resolves https://trello.com/c/NKOlnVI4
=> Resolves issue with pressing ESC with settings open

Assets/Scenes/02_HuntingNew.unity
Removed cube, made new barriers, blocked player from getting stuck in tower
=> Barrier2.0

Assets/Prefabs/UI/General/Developer Console.prefab, Assets/Prefabs/UI/General/Interact Popup Canvas.prefab, Assets/Prefabs/UI/Inventory/Inventory.prefab, Assets/Scenes/01_House.unity, Assets/Scenes/02_HuntingNew.unity
UI now scales correctly. Should appear correctly on non-1920x1080 screens
=> Set UI scales to scale

Assets/Scenes/01_House.unity, Assets/Scenes/02_Hunting.unity, Assets/Scenes/99_LoadingScene.unity, Assets/Scenes/99_LoadingScene.unity.meta, Assets/Scripts/Managers/HouseManager.cs, Assets/Scripts/Managers/HuntingManager.cs, Assets/Scripts/Others/Door.cs, Assets/Scripts/UI/LoadingText.cs, Assets/Scripts/UI/LoadingText.cs.meta, ProjectSettings/EditorBuildSettings.asset
Adds a fade out and loading scene between house and hunting
=> Added fade and loading screen

Assets/Prefabs/FurniturePlaceable/Placeable_Lamp_Tall.prefab, Assets/Scripts/Furnitures/Placeable/Placeable.cs, Assets/Scripts/Managers/InventoryUIManager.cs, Assets/Scripts/UI/Inventory/Model Preview.cs
Added a new `scaleFactorPreview` field to placeable. Set to 0 to keep default scale factor. Tall lamp's `scaleFactorPreview` is changed to a smaller value.
=> Fixed tall lamp too tall for preview

Assets/Scenes/01_House.unity, Assets/Scripts/Managers/HouseManager.cs, ProjectSettings/EditorBuildSettings.asset
Fixed players able to place furniture in the air and fade blocking ray cast in house scene
=> Floating furniture fix

Assets/Scripts/Weapons/Bullet.cs, Assets/Scripts/Weapons/Gun.cs
Fixed issue where ammo would point a different direction to the way it was travelling
=> Ammo rotation fix
